[package]
name = "pallet-evm-precompile-balances-erc20"
version = "0.1.0"
authors = ["PureStake"]
edition = "2018"
description = "A Precompile to expose a Balances pallet throught an ERC20-compliant precompile."

[dependencies]
log = "0.4"
slices = "0.2.0"

sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }

pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.8" }
pallet-evm = { git = "https://github.com/purestake/frontier", default-features = false, branch = "moonriver-phase-four" }
evm = { version = "0.27.0", default-features = false, features = ["with-codec"] }
precompile-utils = { path = "../utils", default-features = false }
num_enum = { version = "0.5.3", default-features = false }

[dev-dependencies]
sp-runtime = { git="https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
pallet-timestamp = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.8" }
serde = { version = "1.0.100" }
derive_more = { version = "0.99"}
max-encoded-len = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.8", features=["derive"] }
sha3 = "0.8"

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-std/std",
    "sp-core/std",
    "sp-io/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-evm/std",
    "pallet-balances/std",
    "evm/std",
    "precompile-utils/std",
]
