version: "3"

services:
  node:
    image: "purestake/moonbeam:${DOCKERVERSION}"
    restart: unless-stopped
    command: 
      --base-path=/data 
      --chain ${CHAINNAME} 
      --execution wasm 
      --wasm-execution compiled 
      --pruning archive 
      --state-cache-size 1 
      -- 
      --pruning archive 
    volumes:
      - node-data:/data
    ports:
      - "30334:30334"
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"

volumes:
  node-data:

