[package]
name = 'moonbeam'
description = 'Moonbeam Collator'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
version = '0.11.0'
authors = ["PureStake"]
edition = '2018'

[[bin]]
name = 'moonbeam'
path = 'src/main.rs'

[dependencies]
futures = { version = "0.3.1", features = ["compat"] }
moonbeam-cli = { path = "cli", default-features = false }
moonbeam-service = { path = "service", default-features = false }

[dev-dependencies]
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0"
assert_cmd = "0.12"
nix = "0.17"
tempfile = "3.2.0"
hex = "0.4.3"
# required for benchmarking
pallet-xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.8" }
xcm-builder = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.8" }

[features]
default = ["moonbase-runtime", "moonriver-runtime", "moonbeam-runtime"]

moonbase-runtime = ["moonbeam-cli/moonbase-runtime", "moonbeam-service/moonbase-runtime"]
moonriver-runtime = ["moonbeam-cli/moonriver-runtime", "moonbeam-service/moonriver-runtime"]
moonbeam-runtime = ["moonbeam-cli/moonbeam-runtime", "moonbeam-service/moonbeam-runtime"]

test-spec = []

runtime-benchmarks = [
	"moonbeam-cli/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
]
